# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: Bonan Liu
first_name: Bonan
last_name: Liu
email: bonan.liu@uni-muenster.de
description: Ph.D. Candidate in Early Childhood Education and Care
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio" target="_blank">al-folio</a> theme.

# -----------------------------------------------------------------------------
# SEO & Social
# -----------------------------------------------------------------------------
keywords: Early Childhood Education, Posthumanism, Ethnography, More-than-Human, Childhood Studies
url: "https://liubonannan.github.io"

# -----------------------------------------------------------------------------
# Theme & Visuals
# -----------------------------------------------------------------------------
color_scheme: auto  # 自动切换深色/浅色模式
